In [1]:
import random
import numpy as np


In [2]:
rand = np.random.rand(3)
rand

array([0.85719693, 0.89006269, 0.20935143])

In [6]:
array = np.array([10,20,30,40,50])
array1 = np.arange(10,60,10)
array1

array([10, 20, 30, 40, 50])

In [16]:
# reshaping the data 
arr = np.arange(1,10)
new_shapearr = arr.reshape(3,3)
new_shapearr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
score = np.array([55, 68, 72, 40, 95])
new_score = score + 5
print(new_score)
pass_student = new_score > 60
print(pass_student)
average_score = np.mean(new_score)
print(average_score)

[ 60  73  77  45 100]
[False  True  True False  True]
71.0
